name       : gnome-disk-utility
version    : 3.28.3
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.28/gnome-disk-utility-3.28.3.tar.xz : 150d35ccb8932c8b899b18a73c17e2abf36b9620c234186740da36bd18f95285
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
