name       : gnome-disk-utility
version    : 3.38.1
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.38/gnome-disk-utility-3.38.1.tar.xz : d53b85dc1303a1b5ce1e421c1f5c6ac0b318e07cd9a95939d2e1f0959a5ed7d9
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
