name       : gnome-disk-utility
version    : 3.20.2
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-disk-utility/3.20/gnome-disk-utility-3.20.2.tar.xz : ad12ae0f3a2ae9c690ca799dd1f690a8eb238575e0fd8f328b66a96eb9bf2c3d
license    : GPL-2.0
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(udisks2)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(dvdread)
    - pkgconfig(libnotify)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
