name       : gnome-disk-utility
version    : '44.0'
release    : 33
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/44/gnome-disk-utility-44.0.tar.xz : 02031097896cdb37d8717a5823f93e3723d4dfce7fdc4002c9dfcb16b7e7a3ef
homepage   : https://wiki.gnome.org/Apps/Disks
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - desktop-file-utils
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %patch -p1 < $pkgfiles/0001-Install-to-usr-share-xdg-instead.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
