name       : gnome-disk-utility
version    : 3.18.3.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-disk-utility/3.18/gnome-disk-utility-3.18.3.1.tar.xz : 652e6332bcf987b15621ebcefc2c14f360b21b7295f94fded6ecfc40c45ae4e8
license    : GPL-2.0
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
builddeps  :
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(udisks2)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(dvdread)
    - pkgconfig(libnotify)
    - docbook-xml
rundeps    :
    - cryptsetup
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
