name       : gnome-disk-utility
version    : 3.26.1
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.26/gnome-disk-utility-3.26.1.tar.xz : 232ec4c2238902293e9ac8c0e05155a963b2d1941fda36660f070bcc36a55783
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
