name       : gnome-disk-utility
version    : 3.32.1
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.32/gnome-disk-utility-3.32.1.tar.xz : 6f15e0d12e87205712f0779195503cda33cb50c40a421f9b94d0869aa25c7c23
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
