name       : gnome-disk-utility
version    : 3.24.1
release    : 6
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-disk-utility/3.24/gnome-disk-utility-3.24.1.tar.xz : 878f0489947c813b44eb89f5fdc2790d757cd8565f26f22b950d55b8585653a1
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
