name       : gnome-disk-utility
version    : 3.28.1
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.28/gnome-disk-utility-3.28.1.tar.xz : a6394ba55b153c8a43734638603357489ff2545264c932cd763122ad9c9db525
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
