name       : gnome-disk-utility
version    : '42.0'
release    : 30
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/42/gnome-disk-utility-42.0.tar.xz : 1b6564454d67426322cb3bfc5a5558653bfc7dfeea2ae0825b1d08629f01090b
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %patch -p1 < $pkgfiles/0001-Install-to-usr-share-xdg-instead.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
