name       : gnome-disk-utility
version    : 3.24.0
release    : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-disk-utility/3.24/gnome-disk-utility-3.24.0.tar.xz : c5f8b1d8aad3136353e4ad4f33c7635bcb563b1adce59d3338202e260a7f3cf3
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
