name       : gnome-disk-utility
version    : 3.34.4
release    : 17
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.34/gnome-disk-utility-3.34.4.tar.xz : 1ec5a365292016572d336c31b252f726dd86655b0a93eab7be3b3c18ab8bf75c
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
