name       : gnome-disk-utility
version    : 3.38.2
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.38/gnome-disk-utility-3.38.2.tar.xz : 10bedde5494beb34e3a220d6f30d9320c88252feeb8426bd98cefad1836d78e9
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %patch -p1 < $pkgfiles/0001-Install-to-usr-share-xdg-instead.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
