name       : gnome-disk-utility
version    : 3.36.0
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.36/gnome-disk-utility-3.36.0.tar.xz : f4079a9404fb583d5f13a2c04cd9e91cd6a19677ace931839a9ad3b9514db103
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
