name       : gnome-disk-utility
version    : 3.26.2
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/3.26/gnome-disk-utility-3.26.2.tar.xz : aa2b96c2c64d8bde6cf802ff8da5796720d0becb21111342ced0637961e256f2
license    : GPL-2.0
component  : desktop.gnome.core
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
