name       : gnome-disk-utility
version    : '41.0'
release    : 28
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/41/gnome-disk-utility-41.0.tar.xz : 8743c98fd656062ef862933efe30c5be4c6b322ec02eee154ec70d08ed0895df
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %patch -p1 < $pkgfiles/0001-Install-to-usr-share-xdg-instead.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
