name       : gnome-disk-utility
version    : 3.22.1
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-disk-utility/3.22/gnome-disk-utility-3.22.1.tar.xz : a3a4a187549f812e3837ae17dd9fa60afcacd84389d696058de254fe18b51ec3
license    : GPL-2.0
summary    : GNOME frontend for managing disks
description: |
    gnome-disk-utility provides libraries and applications for dealing
    with storage devices.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(udisks2)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(dvdread)
    - pkgconfig(libnotify)
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
